// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"finbot/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockService
func (_mock *MockService) Add(ctx context.Context, userID domain.UserID, bankID int64, amount domain.Money) (domain.Bank, error) {
	ret := _mock.Called(ctx, userID, bankID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 domain.Bank
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, int64, domain.Money) (domain.Bank, error)); ok {
		return returnFunc(ctx, userID, bankID, amount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, int64, domain.Money) domain.Bank); ok {
		r0 = returnFunc(ctx, userID, bankID, amount)
	} else {
		r0 = ret.Get(0).(domain.Bank)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, int64, domain.Money) error); ok {
		r1 = returnFunc(ctx, userID, bankID, amount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockService_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - bankID int64
//   - amount domain.Money
func (_e *MockService_Expecter) Add(ctx interface{}, userID interface{}, bankID interface{}, amount interface{}) *MockService_Add_Call {
	return &MockService_Add_Call{Call: _e.mock.On("Add", ctx, userID, bankID, amount)}
}

func (_c *MockService_Add_Call) Run(run func(ctx context.Context, userID domain.UserID, bankID int64, amount domain.Money)) *MockService_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 domain.Money
		if args[3] != nil {
			arg3 = args[3].(domain.Money)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Add_Call) Return(bank domain.Bank, err error) *MockService_Add_Call {
	_c.Call.Return(bank, err)
	return _c
}

func (_c *MockService_Add_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, bankID int64, amount domain.Money) (domain.Bank, error)) *MockService_Add_Call {
	_c.Call.Return(run)
	return _c
}

// All provides a mock function for the type MockService
func (_mock *MockService) All(ctx context.Context, userID domain.UserID) ([]domain.Bank, domain.Money, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []domain.Bank
	var r1 domain.Money
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) ([]domain.Bank, domain.Money, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) []domain.Bank); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Bank)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID) domain.Money); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Get(1).(domain.Money)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.UserID) error); ok {
		r2 = returnFunc(ctx, userID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockService_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
func (_e *MockService_Expecter) All(ctx interface{}, userID interface{}) *MockService_All_Call {
	return &MockService_All_Call{Call: _e.mock.On("All", ctx, userID)}
}

func (_c *MockService_All_Call) Run(run func(ctx context.Context, userID domain.UserID)) *MockService_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_All_Call) Return(banks []domain.Bank, money domain.Money, err error) *MockService_All_Call {
	_c.Call.Return(banks, money, err)
	return _c
}

func (_c *MockService_All_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID) ([]domain.Bank, domain.Money, error)) *MockService_All_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBank provides a mock function for the type MockService
func (_mock *MockService) CreateBank(ctx context.Context, userID domain.UserID, name string, includeInTotal bool) (domain.Bank, error) {
	ret := _mock.Called(ctx, userID, name, includeInTotal)

	if len(ret) == 0 {
		panic("no return value specified for CreateBank")
	}

	var r0 domain.Bank
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, string, bool) (domain.Bank, error)); ok {
		return returnFunc(ctx, userID, name, includeInTotal)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, string, bool) domain.Bank); ok {
		r0 = returnFunc(ctx, userID, name, includeInTotal)
	} else {
		r0 = ret.Get(0).(domain.Bank)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, string, bool) error); ok {
		r1 = returnFunc(ctx, userID, name, includeInTotal)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateBank_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBank'
type MockService_CreateBank_Call struct {
	*mock.Call
}

// CreateBank is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - name string
//   - includeInTotal bool
func (_e *MockService_Expecter) CreateBank(ctx interface{}, userID interface{}, name interface{}, includeInTotal interface{}) *MockService_CreateBank_Call {
	return &MockService_CreateBank_Call{Call: _e.mock.On("CreateBank", ctx, userID, name, includeInTotal)}
}

func (_c *MockService_CreateBank_Call) Run(run func(ctx context.Context, userID domain.UserID, name string, includeInTotal bool)) *MockService_CreateBank_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_CreateBank_Call) Return(bank domain.Bank, err error) *MockService_CreateBank_Call {
	_c.Call.Return(bank, err)
	return _c
}

func (_c *MockService_CreateBank_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, name string, includeInTotal bool) (domain.Bank, error)) *MockService_CreateBank_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockService
func (_mock *MockService) Delete(ctx context.Context, userID domain.UserID, bankID int64) error {
	ret := _mock.Called(ctx, userID, bankID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, int64) error); ok {
		r0 = returnFunc(ctx, userID, bankID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - bankID int64
func (_e *MockService_Expecter) Delete(ctx interface{}, userID interface{}, bankID interface{}) *MockService_Delete_Call {
	return &MockService_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, bankID)}
}

func (_c *MockService_Delete_Call) Run(run func(ctx context.Context, userID domain.UserID, bankID int64)) *MockService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Delete_Call) Return(err error) *MockService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_Delete_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, bankID int64) error) *MockService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockService
func (_mock *MockService) Get(ctx context.Context, userID domain.UserID, bankID int64) (domain.Bank, error) {
	ret := _mock.Called(ctx, userID, bankID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Bank
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, int64) (domain.Bank, error)); ok {
		return returnFunc(ctx, userID, bankID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, int64) domain.Bank); ok {
		r0 = returnFunc(ctx, userID, bankID)
	} else {
		r0 = ret.Get(0).(domain.Bank)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, int64) error); ok {
		r1 = returnFunc(ctx, userID, bankID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - bankID int64
func (_e *MockService_Expecter) Get(ctx interface{}, userID interface{}, bankID interface{}) *MockService_Get_Call {
	return &MockService_Get_Call{Call: _e.mock.On("Get", ctx, userID, bankID)}
}

func (_c *MockService_Get_Call) Run(run func(ctx context.Context, userID domain.UserID, bankID int64)) *MockService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Get_Call) Return(bank domain.Bank, err error) *MockService_Get_Call {
	_c.Call.Return(bank, err)
	return _c
}

func (_c *MockService_Get_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, bankID int64) (domain.Bank, error)) *MockService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockService
func (_mock *MockService) GetByName(ctx context.Context, userID domain.UserID, name string) (domain.Bank, error) {
	ret := _mock.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 domain.Bank
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, string) (domain.Bank, error)); ok {
		return returnFunc(ctx, userID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, string) domain.Bank); ok {
		r0 = returnFunc(ctx, userID, name)
	} else {
		r0 = ret.Get(0).(domain.Bank)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, string) error); ok {
		r1 = returnFunc(ctx, userID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockService_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - name string
func (_e *MockService_Expecter) GetByName(ctx interface{}, userID interface{}, name interface{}) *MockService_GetByName_Call {
	return &MockService_GetByName_Call{Call: _e.mock.On("GetByName", ctx, userID, name)}
}

func (_c *MockService_GetByName_Call) Run(run func(ctx context.Context, userID domain.UserID, name string)) *MockService_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_GetByName_Call) Return(bank domain.Bank, err error) *MockService_GetByName_Call {
	_c.Call.Return(bank, err)
	return _c
}

func (_c *MockService_GetByName_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, name string) (domain.Bank, error)) *MockService_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockService
func (_mock *MockService) List(ctx context.Context, userID domain.UserID) ([]domain.Bank, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Bank
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) ([]domain.Bank, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) []domain.Bank); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Bank)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
func (_e *MockService_Expecter) List(ctx interface{}, userID interface{}) *MockService_List_Call {
	return &MockService_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *MockService_List_Call) Run(run func(ctx context.Context, userID domain.UserID)) *MockService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_List_Call) Return(banks []domain.Bank, err error) *MockService_List_Call {
	_c.Call.Return(banks, err)
	return _c
}

func (_c *MockService_List_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID) ([]domain.Bank, error)) *MockService_List_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockService
func (_mock *MockService) Set(ctx context.Context, userID domain.UserID, bankID int64, amount domain.Money) (domain.Bank, error) {
	ret := _mock.Called(ctx, userID, bankID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 domain.Bank
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, int64, domain.Money) (domain.Bank, error)); ok {
		return returnFunc(ctx, userID, bankID, amount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, int64, domain.Money) domain.Bank); ok {
		r0 = returnFunc(ctx, userID, bankID, amount)
	} else {
		r0 = ret.Get(0).(domain.Bank)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, int64, domain.Money) error); ok {
		r1 = returnFunc(ctx, userID, bankID, amount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockService_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - bankID int64
//   - amount domain.Money
func (_e *MockService_Expecter) Set(ctx interface{}, userID interface{}, bankID interface{}, amount interface{}) *MockService_Set_Call {
	return &MockService_Set_Call{Call: _e.mock.On("Set", ctx, userID, bankID, amount)}
}

func (_c *MockService_Set_Call) Run(run func(ctx context.Context, userID domain.UserID, bankID int64, amount domain.Money)) *MockService_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 domain.Money
		if args[3] != nil {
			arg3 = args[3].(domain.Money)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Set_Call) Return(bank domain.Bank, err error) *MockService_Set_Call {
	_c.Call.Return(bank, err)
	return _c
}

func (_c *MockService_Set_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, bankID int64, amount domain.Money) (domain.Bank, error)) *MockService_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetReferredByIfEmpty provides a mock function for the type MockService
func (_mock *MockService) SetReferredByIfEmpty(ctx context.Context, userID domain.UserID, referredBy domain.UserID) error {
	ret := _mock.Called(ctx, userID, referredBy)

	if len(ret) == 0 {
		panic("no return value specified for SetReferredByIfEmpty")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, domain.UserID) error); ok {
		r0 = returnFunc(ctx, userID, referredBy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SetReferredByIfEmpty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReferredByIfEmpty'
type MockService_SetReferredByIfEmpty_Call struct {
	*mock.Call
}

// SetReferredByIfEmpty is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - referredBy domain.UserID
func (_e *MockService_Expecter) SetReferredByIfEmpty(ctx interface{}, userID interface{}, referredBy interface{}) *MockService_SetReferredByIfEmpty_Call {
	return &MockService_SetReferredByIfEmpty_Call{Call: _e.mock.On("SetReferredByIfEmpty", ctx, userID, referredBy)}
}

func (_c *MockService_SetReferredByIfEmpty_Call) Run(run func(ctx context.Context, userID domain.UserID, referredBy domain.UserID)) *MockService_SetReferredByIfEmpty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 domain.UserID
		if args[2] != nil {
			arg2 = args[2].(domain.UserID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_SetReferredByIfEmpty_Call) Return(err error) *MockService_SetReferredByIfEmpty_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SetReferredByIfEmpty_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, referredBy domain.UserID) error) *MockService_SetReferredByIfEmpty_Call {
	_c.Call.Return(run)
	return _c
}

// Spend provides a mock function for the type MockService
func (_mock *MockService) Spend(ctx context.Context, userID domain.UserID, bankID int64, amount domain.Money) (domain.Bank, error) {
	ret := _mock.Called(ctx, userID, bankID, amount)

	if len(ret) == 0 {
		panic("no return value specified for Spend")
	}

	var r0 domain.Bank
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, int64, domain.Money) (domain.Bank, error)); ok {
		return returnFunc(ctx, userID, bankID, amount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, int64, domain.Money) domain.Bank); ok {
		r0 = returnFunc(ctx, userID, bankID, amount)
	} else {
		r0 = ret.Get(0).(domain.Bank)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, int64, domain.Money) error); ok {
		r1 = returnFunc(ctx, userID, bankID, amount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Spend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Spend'
type MockService_Spend_Call struct {
	*mock.Call
}

// Spend is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - bankID int64
//   - amount domain.Money
func (_e *MockService_Expecter) Spend(ctx interface{}, userID interface{}, bankID interface{}, amount interface{}) *MockService_Spend_Call {
	return &MockService_Spend_Call{Call: _e.mock.On("Spend", ctx, userID, bankID, amount)}
}

func (_c *MockService_Spend_Call) Run(run func(ctx context.Context, userID domain.UserID, bankID int64, amount domain.Money)) *MockService_Spend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 domain.Money
		if args[3] != nil {
			arg3 = args[3].(domain.Money)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_Spend_Call) Return(bank domain.Bank, err error) *MockService_Spend_Call {
	_c.Call.Return(bank, err)
	return _c
}

func (_c *MockService_Spend_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, bankID int64, amount domain.Money) (domain.Bank, error)) *MockService_Spend_Call {
	_c.Call.Return(run)
	return _c
}

// Toggle provides a mock function for the type MockService
func (_mock *MockService) Toggle(ctx context.Context, userID domain.UserID, bankID int64) (domain.Bank, error) {
	ret := _mock.Called(ctx, userID, bankID)

	if len(ret) == 0 {
		panic("no return value specified for Toggle")
	}

	var r0 domain.Bank
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, int64) (domain.Bank, error)); ok {
		return returnFunc(ctx, userID, bankID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, int64) domain.Bank); ok {
		r0 = returnFunc(ctx, userID, bankID)
	} else {
		r0 = ret.Get(0).(domain.Bank)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, int64) error); ok {
		r1 = returnFunc(ctx, userID, bankID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Toggle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Toggle'
type MockService_Toggle_Call struct {
	*mock.Call
}

// Toggle is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - bankID int64
func (_e *MockService_Expecter) Toggle(ctx interface{}, userID interface{}, bankID interface{}) *MockService_Toggle_Call {
	return &MockService_Toggle_Call{Call: _e.mock.On("Toggle", ctx, userID, bankID)}
}

func (_c *MockService_Toggle_Call) Run(run func(ctx context.Context, userID domain.UserID, bankID int64)) *MockService_Toggle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_Toggle_Call) Return(bank domain.Bank, err error) *MockService_Toggle_Call {
	_c.Call.Return(bank, err)
	return _c
}

func (_c *MockService_Toggle_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, bankID int64) (domain.Bank, error)) *MockService_Toggle_Call {
	_c.Call.Return(run)
	return _c
}

// Total provides a mock function for the type MockService
func (_mock *MockService) Total(ctx context.Context, userID domain.UserID) (domain.Money, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Total")
	}

	var r0 domain.Money
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) (domain.Money, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) domain.Money); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.Money)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Total_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Total'
type MockService_Total_Call struct {
	*mock.Call
}

// Total is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
func (_e *MockService_Expecter) Total(ctx interface{}, userID interface{}) *MockService_Total_Call {
	return &MockService_Total_Call{Call: _e.mock.On("Total", ctx, userID)}
}

func (_c *MockService_Total_Call) Run(run func(ctx context.Context, userID domain.UserID)) *MockService_Total_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Total_Call) Return(money domain.Money, err error) *MockService_Total_Call {
	_c.Call.Return(money, err)
	return _c
}

func (_c *MockService_Total_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID) (domain.Money, error)) *MockService_Total_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUser provides a mock function for the type MockService
func (_mock *MockService) UpsertUser(ctx context.Context, userID domain.UserID, username string) (domain.User, error) {
	ret := _mock.Called(ctx, userID, username)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, string) (domain.User, error)); ok {
		return returnFunc(ctx, userID, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, string) domain.User); ok {
		r0 = returnFunc(ctx, userID, username)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, string) error); ok {
		r1 = returnFunc(ctx, userID, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UpsertUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUser'
type MockService_UpsertUser_Call struct {
	*mock.Call
}

// UpsertUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - username string
func (_e *MockService_Expecter) UpsertUser(ctx interface{}, userID interface{}, username interface{}) *MockService_UpsertUser_Call {
	return &MockService_UpsertUser_Call{Call: _e.mock.On("UpsertUser", ctx, userID, username)}
}

func (_c *MockService_UpsertUser_Call) Run(run func(ctx context.Context, userID domain.UserID, username string)) *MockService_UpsertUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_UpsertUser_Call) Return(user domain.User, err error) *MockService_UpsertUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockService_UpsertUser_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, username string) (domain.User, error)) *MockService_UpsertUser_Call {
	_c.Call.Return(run)
	return _c
}
