// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"finbot/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBankRepository creates a new instance of MockBankRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBankRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBankRepository {
	mock := &MockBankRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBankRepository is an autogenerated mock type for the BankRepository type
type MockBankRepository struct {
	mock.Mock
}

type MockBankRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBankRepository) EXPECT() *MockBankRepository_Expecter {
	return &MockBankRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockBankRepository
func (_mock *MockBankRepository) Create(ctx context.Context, userID domain.UserID, bank domain.Bank) (domain.Bank, error) {
	ret := _mock.Called(ctx, userID, bank)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Bank
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, domain.Bank) (domain.Bank, error)); ok {
		return returnFunc(ctx, userID, bank)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, domain.Bank) domain.Bank); ok {
		r0 = returnFunc(ctx, userID, bank)
	} else {
		r0 = ret.Get(0).(domain.Bank)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, domain.Bank) error); ok {
		r1 = returnFunc(ctx, userID, bank)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBankRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBankRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - bank domain.Bank
func (_e *MockBankRepository_Expecter) Create(ctx interface{}, userID interface{}, bank interface{}) *MockBankRepository_Create_Call {
	return &MockBankRepository_Create_Call{Call: _e.mock.On("Create", ctx, userID, bank)}
}

func (_c *MockBankRepository_Create_Call) Run(run func(ctx context.Context, userID domain.UserID, bank domain.Bank)) *MockBankRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 domain.Bank
		if args[2] != nil {
			arg2 = args[2].(domain.Bank)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBankRepository_Create_Call) Return(bank1 domain.Bank, err error) *MockBankRepository_Create_Call {
	_c.Call.Return(bank1, err)
	return _c
}

func (_c *MockBankRepository_Create_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, bank domain.Bank) (domain.Bank, error)) *MockBankRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockBankRepository
func (_mock *MockBankRepository) Delete(ctx context.Context, userID domain.UserID, bankID int64) error {
	ret := _mock.Called(ctx, userID, bankID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, int64) error); ok {
		r0 = returnFunc(ctx, userID, bankID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBankRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBankRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - bankID int64
func (_e *MockBankRepository_Expecter) Delete(ctx interface{}, userID interface{}, bankID interface{}) *MockBankRepository_Delete_Call {
	return &MockBankRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, userID, bankID)}
}

func (_c *MockBankRepository_Delete_Call) Run(run func(ctx context.Context, userID domain.UserID, bankID int64)) *MockBankRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBankRepository_Delete_Call) Return(err error) *MockBankRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBankRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, bankID int64) error) *MockBankRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockBankRepository
func (_mock *MockBankRepository) GetByID(ctx context.Context, userID domain.UserID, bankID int64) (domain.Bank, error) {
	ret := _mock.Called(ctx, userID, bankID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Bank
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, int64) (domain.Bank, error)); ok {
		return returnFunc(ctx, userID, bankID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, int64) domain.Bank); ok {
		r0 = returnFunc(ctx, userID, bankID)
	} else {
		r0 = ret.Get(0).(domain.Bank)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, int64) error); ok {
		r1 = returnFunc(ctx, userID, bankID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBankRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockBankRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - bankID int64
func (_e *MockBankRepository_Expecter) GetByID(ctx interface{}, userID interface{}, bankID interface{}) *MockBankRepository_GetByID_Call {
	return &MockBankRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID, bankID)}
}

func (_c *MockBankRepository_GetByID_Call) Run(run func(ctx context.Context, userID domain.UserID, bankID int64)) *MockBankRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBankRepository_GetByID_Call) Return(bank domain.Bank, err error) *MockBankRepository_GetByID_Call {
	_c.Call.Return(bank, err)
	return _c
}

func (_c *MockBankRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, bankID int64) (domain.Bank, error)) *MockBankRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockBankRepository
func (_mock *MockBankRepository) GetByName(ctx context.Context, userID domain.UserID, name string) (domain.Bank, error) {
	ret := _mock.Called(ctx, userID, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 domain.Bank
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, string) (domain.Bank, error)); ok {
		return returnFunc(ctx, userID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, string) domain.Bank); ok {
		r0 = returnFunc(ctx, userID, name)
	} else {
		r0 = ret.Get(0).(domain.Bank)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, string) error); ok {
		r1 = returnFunc(ctx, userID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBankRepository_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockBankRepository_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - name string
func (_e *MockBankRepository_Expecter) GetByName(ctx interface{}, userID interface{}, name interface{}) *MockBankRepository_GetByName_Call {
	return &MockBankRepository_GetByName_Call{Call: _e.mock.On("GetByName", ctx, userID, name)}
}

func (_c *MockBankRepository_GetByName_Call) Run(run func(ctx context.Context, userID domain.UserID, name string)) *MockBankRepository_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBankRepository_GetByName_Call) Return(bank domain.Bank, err error) *MockBankRepository_GetByName_Call {
	_c.Call.Return(bank, err)
	return _c
}

func (_c *MockBankRepository_GetByName_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, name string) (domain.Bank, error)) *MockBankRepository_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockBankRepository
func (_mock *MockBankRepository) List(ctx context.Context, userID domain.UserID) ([]domain.Bank, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Bank
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) ([]domain.Bank, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) []domain.Bank); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Bank)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBankRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBankRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
func (_e *MockBankRepository_Expecter) List(ctx interface{}, userID interface{}) *MockBankRepository_List_Call {
	return &MockBankRepository_List_Call{Call: _e.mock.On("List", ctx, userID)}
}

func (_c *MockBankRepository_List_Call) Run(run func(ctx context.Context, userID domain.UserID)) *MockBankRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBankRepository_List_Call) Return(banks []domain.Bank, err error) *MockBankRepository_List_Call {
	_c.Call.Return(banks, err)
	return _c
}

func (_c *MockBankRepository_List_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID) ([]domain.Bank, error)) *MockBankRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// TotalIncluded provides a mock function for the type MockBankRepository
func (_mock *MockBankRepository) TotalIncluded(ctx context.Context, userID domain.UserID) (domain.Money, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for TotalIncluded")
	}

	var r0 domain.Money
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) (domain.Money, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID) domain.Money); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(domain.Money)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBankRepository_TotalIncluded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TotalIncluded'
type MockBankRepository_TotalIncluded_Call struct {
	*mock.Call
}

// TotalIncluded is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
func (_e *MockBankRepository_Expecter) TotalIncluded(ctx interface{}, userID interface{}) *MockBankRepository_TotalIncluded_Call {
	return &MockBankRepository_TotalIncluded_Call{Call: _e.mock.On("TotalIncluded", ctx, userID)}
}

func (_c *MockBankRepository_TotalIncluded_Call) Run(run func(ctx context.Context, userID domain.UserID)) *MockBankRepository_TotalIncluded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBankRepository_TotalIncluded_Call) Return(money domain.Money, err error) *MockBankRepository_TotalIncluded_Call {
	_c.Call.Return(money, err)
	return _c
}

func (_c *MockBankRepository_TotalIncluded_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID) (domain.Money, error)) *MockBankRepository_TotalIncluded_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockBankRepository
func (_mock *MockBankRepository) Update(ctx context.Context, userID domain.UserID, bank domain.Bank) (domain.Bank, error) {
	ret := _mock.Called(ctx, userID, bank)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Bank
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, domain.Bank) (domain.Bank, error)); ok {
		return returnFunc(ctx, userID, bank)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, domain.Bank) domain.Bank); ok {
		r0 = returnFunc(ctx, userID, bank)
	} else {
		r0 = ret.Get(0).(domain.Bank)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.UserID, domain.Bank) error); ok {
		r1 = returnFunc(ctx, userID, bank)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBankRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBankRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - bank domain.Bank
func (_e *MockBankRepository_Expecter) Update(ctx interface{}, userID interface{}, bank interface{}) *MockBankRepository_Update_Call {
	return &MockBankRepository_Update_Call{Call: _e.mock.On("Update", ctx, userID, bank)}
}

func (_c *MockBankRepository_Update_Call) Run(run func(ctx context.Context, userID domain.UserID, bank domain.Bank)) *MockBankRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 domain.Bank
		if args[2] != nil {
			arg2 = args[2].(domain.Bank)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBankRepository_Update_Call) Return(bank1 domain.Bank, err error) *MockBankRepository_Update_Call {
	_c.Call.Return(bank1, err)
	return _c
}

func (_c *MockBankRepository_Update_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, bank domain.Bank) (domain.Bank, error)) *MockBankRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
