// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"finbot/internal/domain"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// SetLocale provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) SetLocale(ctx context.Context, userID domain.UserID, locale string, at time.Time) error {
	ret := _mock.Called(ctx, userID, locale, at)

	if len(ret) == 0 {
		panic("no return value specified for SetLocale")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, string, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, locale, at)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_SetLocale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLocale'
type MockUserRepository_SetLocale_Call struct {
	*mock.Call
}

// SetLocale is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - locale string
//   - at time.Time
func (_e *MockUserRepository_Expecter) SetLocale(ctx interface{}, userID interface{}, locale interface{}, at interface{}) *MockUserRepository_SetLocale_Call {
	return &MockUserRepository_SetLocale_Call{Call: _e.mock.On("SetLocale", ctx, userID, locale, at)}
}

func (_c *MockUserRepository_SetLocale_Call) Run(run func(ctx context.Context, userID domain.UserID, locale string, at time.Time)) *MockUserRepository_SetLocale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserRepository_SetLocale_Call) Return(err error) *MockUserRepository_SetLocale_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_SetLocale_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, locale string, at time.Time) error) *MockUserRepository_SetLocale_Call {
	_c.Call.Return(run)
	return _c
}

// SetReferredByIfEmpty provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) SetReferredByIfEmpty(ctx context.Context, userID domain.UserID, referredBy domain.UserID) error {
	ret := _mock.Called(ctx, userID, referredBy)

	if len(ret) == 0 {
		panic("no return value specified for SetReferredByIfEmpty")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, domain.UserID) error); ok {
		r0 = returnFunc(ctx, userID, referredBy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_SetReferredByIfEmpty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetReferredByIfEmpty'
type MockUserRepository_SetReferredByIfEmpty_Call struct {
	*mock.Call
}

// SetReferredByIfEmpty is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - referredBy domain.UserID
func (_e *MockUserRepository_Expecter) SetReferredByIfEmpty(ctx interface{}, userID interface{}, referredBy interface{}) *MockUserRepository_SetReferredByIfEmpty_Call {
	return &MockUserRepository_SetReferredByIfEmpty_Call{Call: _e.mock.On("SetReferredByIfEmpty", ctx, userID, referredBy)}
}

func (_c *MockUserRepository_SetReferredByIfEmpty_Call) Run(run func(ctx context.Context, userID domain.UserID, referredBy domain.UserID)) *MockUserRepository_SetReferredByIfEmpty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 domain.UserID
		if args[2] != nil {
			arg2 = args[2].(domain.UserID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_SetReferredByIfEmpty_Call) Return(err error) *MockUserRepository_SetReferredByIfEmpty_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_SetReferredByIfEmpty_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, referredBy domain.UserID) error) *MockUserRepository_SetReferredByIfEmpty_Call {
	_c.Call.Return(run)
	return _c
}

// TouchActivity provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) TouchActivity(ctx context.Context, userID domain.UserID, at time.Time) error {
	ret := _mock.Called(ctx, userID, at)

	if len(ret) == 0 {
		panic("no return value specified for TouchActivity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, time.Time) error); ok {
		r0 = returnFunc(ctx, userID, at)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_TouchActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TouchActivity'
type MockUserRepository_TouchActivity_Call struct {
	*mock.Call
}

// TouchActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - at time.Time
func (_e *MockUserRepository_Expecter) TouchActivity(ctx interface{}, userID interface{}, at interface{}) *MockUserRepository_TouchActivity_Call {
	return &MockUserRepository_TouchActivity_Call{Call: _e.mock.On("TouchActivity", ctx, userID, at)}
}

func (_c *MockUserRepository_TouchActivity_Call) Run(run func(ctx context.Context, userID domain.UserID, at time.Time)) *MockUserRepository_TouchActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_TouchActivity_Call) Return(err error) *MockUserRepository_TouchActivity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_TouchActivity_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, at time.Time) error) *MockUserRepository_TouchActivity_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Upsert(ctx context.Context, user domain.User) (domain.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) (domain.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type MockUserRepository_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockUserRepository_Expecter) Upsert(ctx interface{}, user interface{}) *MockUserRepository_Upsert_Call {
	return &MockUserRepository_Upsert_Call{Call: _e.mock.On("Upsert", ctx, user)}
}

func (_c *MockUserRepository_Upsert_Call) Run(run func(ctx context.Context, user domain.User)) *MockUserRepository_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Upsert_Call) Return(user1 domain.User, err error) *MockUserRepository_Upsert_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepository_Upsert_Call) RunAndReturn(run func(ctx context.Context, user domain.User) (domain.User, error)) *MockUserRepository_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
