// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"finbot/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOperationRepository creates a new instance of MockOperationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOperationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOperationRepository {
	mock := &MockOperationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOperationRepository is an autogenerated mock type for the OperationRepository type
type MockOperationRepository struct {
	mock.Mock
}

type MockOperationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOperationRepository) EXPECT() *MockOperationRepository_Expecter {
	return &MockOperationRepository_Expecter{mock: &_m.Mock}
}

// Append provides a mock function for the type MockOperationRepository
func (_mock *MockOperationRepository) Append(ctx context.Context, op domain.Operation) error {
	ret := _mock.Called(ctx, op)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Operation) error); ok {
		r0 = returnFunc(ctx, op)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOperationRepository_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockOperationRepository_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - op domain.Operation
func (_e *MockOperationRepository_Expecter) Append(ctx interface{}, op interface{}) *MockOperationRepository_Append_Call {
	return &MockOperationRepository_Append_Call{Call: _e.mock.On("Append", ctx, op)}
}

func (_c *MockOperationRepository_Append_Call) Run(run func(ctx context.Context, op domain.Operation)) *MockOperationRepository_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Operation
		if args[1] != nil {
			arg1 = args[1].(domain.Operation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOperationRepository_Append_Call) Return(err error) *MockOperationRepository_Append_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOperationRepository_Append_Call) RunAndReturn(run func(ctx context.Context, op domain.Operation) error) *MockOperationRepository_Append_Call {
	_c.Call.Return(run)
	return _c
}
