// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"finbot/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifier {
	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

type MockNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifier) EXPECT() *MockNotifier_Expecter {
	return &MockNotifier_Expecter{mock: &_m.Mock}
}

// Notify provides a mock function for the type MockNotifier
func (_mock *MockNotifier) Notify(ctx context.Context, userID domain.UserID, message string) error {
	ret := _mock.Called(ctx, userID, message)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserID, string) error); ok {
		r0 = returnFunc(ctx, userID, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotifier_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockNotifier_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - ctx context.Context
//   - userID domain.UserID
//   - message string
func (_e *MockNotifier_Expecter) Notify(ctx interface{}, userID interface{}, message interface{}) *MockNotifier_Notify_Call {
	return &MockNotifier_Notify_Call{Call: _e.mock.On("Notify", ctx, userID, message)}
}

func (_c *MockNotifier_Notify_Call) Run(run func(ctx context.Context, userID domain.UserID, message string)) *MockNotifier_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserID
		if args[1] != nil {
			arg1 = args[1].(domain.UserID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNotifier_Notify_Call) Return(err error) *MockNotifier_Notify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotifier_Notify_Call) RunAndReturn(run func(ctx context.Context, userID domain.UserID, message string) error) *MockNotifier_Notify_Call {
	_c.Call.Return(run)
	return _c
}
