CREATE TABLE users (
    telegram_id BIGINT PRIMARY KEY,
    username TEXT,
    last_activity_at TIMESTAMPTZ NOT NULL,
    plan TEXT NOT NULL DEFAULT 'trial',
    trial_ends_at TIMESTAMPTZ NOT NULL,
    discount_percent INTEGER,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    locale TEXT NOT NULL DEFAULT 'en',
    referred_by BIGINT,
    CHECK (discount_percent IS NULL OR (discount_percent >= 0 AND discount_percent <= 100))
);

CREATE TABLE banks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (telegram_id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    name_normalized TEXT NOT NULL,
    balance_cents BIGINT NOT NULL DEFAULT 0,
    include_in_total BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    currency TEXT NOT NULL DEFAULT 'USD',
    UNIQUE (user_id, name_normalized)
);

CREATE TABLE operations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (telegram_id) ON DELETE CASCADE,
    bank_id BIGINT REFERENCES banks (id) ON DELETE SET NULL,
    type TEXT NOT NULL,
    amount_cents BIGINT NOT NULL,
    balance_after_cents BIGINT,
    meta TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    CHECK (type IN ('add', 'spend', 'set', 'delete', 'transfer', 'rename'))
);

CREATE INDEX idx_banks_user_id ON banks (user_id);
CREATE INDEX idx_operations_user_created_at ON operations (user_id, created_at DESC);
CREATE INDEX idx_operations_bank_id ON operations (bank_id);
CREATE INDEX idx_users_last_activity_at ON users (last_activity_at);
